print('"A arte pode vencer a natureza, desde que o artista deixe nela a sua marca."" ')
print(' ')
print("Viver \n significa \n lutar. ")
print(' ')
print('Fácil é sonhar todas as noites. \n Difícil é lutar por um sonho.')
